name: block_pong_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.3.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  frame:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
